name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Build wheel on cp${{ matrix.python }}-${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # manylinux builds
          - os: ubuntu-latest
            python: "36"
            platform: manylinux_x86_64
          - os: ubuntu-latest
            python: "37"
            platform: manylinux_x86_64
          - os: ubuntu-latest
            python: "38"
            platform: manylinux_x86_64
          
          # macos builds
          - os: macos-latest
            python: "36"
            platform: macosx_x86_64
          - os: macos-latest
            python: "37"
            platform: macosx_x86_64
          - os: macos-latest
            python: "38"
            platform: macosx_x86_64

          # windows builds
          - os: windows-latest
            python: "36"
            platform: win_amd64
          - os: windows-latest
            python: "37"
            platform: win_amd64
          - os: windows-latest
            python: "38"
            platform: win_amd64

    steps:
      - uses: actions/checkout@v2
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.3
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD_VERBOSITY: 3
          CIBW_TEST_COMMAND: python -c "import cython_bbox"
